version: '3'

services:
  proxied:
    build:
      context: /2-server-proxied
      dockerfile: Dockerfile
    image: joanaws/2-server-proxied:composed
    container_name: ${PROXIED_SERVER_HOSTNAME}
  
  proxy:
    build:
      context: /1-server-proxy
      dockerfile: Dockerfile
    image: joanaws/1-server-proxy:composed
    volumes:
      - ./1-server-proxy/templates:/etc/nginx/templates
    depends_on:
      - proxied
    # env_file:
    #   - .env
    environment:
      PROXY_SERVER_PORT: ${PROXY_SERVER_PORT}
      PROXIED_SERVER_HOSTNAME: ${PROXIED_SERVER_HOSTNAME}
      PROXIED_SERVER_PORT: ${PROXIED_SERVER_PORT}
    container_name: c-proxy-server
    ports:
      - ${PROXY_SERVER_PORT}:80
    