version: '3'

services:
  proxied:
    build:
      context: /2-server-proxied
      dockerfile: Dockerfile
      args: # Pasa el argumento al Dockerfile, ya que ARG solo está disponible en tiempo de build.
        PROXIED_SERVER_PORT: ${PROXIED_SERVER_PORT} # Se pasa para que sea reemplazado en la capa EXPOSE del Dockerfile
    volumes:
      - ./2-server-proxied/templates:/etc/nginx/templates
    image: joanaws/2-server-proxied:composed
    container_name: ${PROXIED_SERVER_HOSTNAME}
    environment:
      PROXIED_SERVER_PORT: ${PROXIED_SERVER_PORT}
  proxy:
    build:
      context: /1-server-proxy
      dockerfile: Dockerfile
      args: # Pasa el argumento al Dockerfile, ya que ARG solo está disponible en tiempo de build.
        PROXY_SERVER_PORT: ${PROXY_SERVER_PORT} # Se pasa para que sea reemplazado en la capa EXPOSE del Dockerfile
    image: joanaws/1-server-proxy:composed
    volumes:
      - ./1-server-proxy/templates:/etc/nginx/templates
    depends_on:
      - proxied
    # env_file:
    #   - .env
    environment:
      PROXY_SERVER_PORT: ${PROXY_SERVER_PORT}
      PROXIED_SERVER_HOSTNAME: ${PROXIED_SERVER_HOSTNAME}
      PROXIED_SERVER_PORT: ${PROXIED_SERVER_PORT}
    container_name: reverse-proxy-server
    ports:
      - ${PROXY_SERVER_PORT}:${PROXY_SERVER_PORT}
    